# Generated by Django 6.0.3 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('prazo', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('nova', 'Nova'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='nova', max_length=20)),
            ],
        ),
    ]
